[package]
name = "vst3"
version = "0.1.0"
edition = "2021"

[dependencies]
bytemuck = {version = "1.16.1", features = ["min_const_generics", "nightly_docs", "const_zeroed"]}
paste = "1.0.15"
static_assertions = "1.1.0"
